### ISSUE TITLE
returning undefined instead of null

### ISSUE THREAD

**Issue by hville** [sorensen/try-json.js#1]
Not a big deal but since `null` is a valid JSON type wouldn't it be more consistent to return `undefined` on invalid JSON? Although unlikely, `JSON.parse("null")` is a valid JSON expression that would return `null`. Undefined does not exist in JSON and would truly mean that the parsing failed.

**Comment by sorensen** [comment]
Agreed, it has been something I've been meaning to do for a while. Thanks for opening the issue.

**Comment by radiovisual** [comment]
shouldn't this issue be closed? this module returns `undefined` ever since the [last commit](https://github.com/sorensen/try-json.js/commit/a1f6891acbfbeedae9fce663d825f073a3315c8b).
